create table if not exists public.association_members (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    image_url text,
    display_order integer,
    created_at timestamptz not null default now()
);

create index if not exists association_members_display_order_idx
    on public.association_members (display_order, name);
